version: '3.8'

services:
  # Microservicio de Pedidos
  order-service:
    image: saul-isus/order-service:latest
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      # Conexión dinámica a la Base de Datos
      - DB_ORDER_URL=jdbc:postgresql://postgres-db:5432/order_db
      - DB_ORDER_USER=saul_admin
      - DB_ORDER_PASSWORD=secret_pass
      # Ruta dinámica para comunicarse con otros microservicios
      - INVENTORY_SERVICE_URL=http://inventory-service:8082
    depends_on:
      - postgres-db

  # Base de Datos PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=saul_admin
      - POSTGRES_PASSWORD=secret_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: