server:
  port: 8081

spring:
  application:
    name: order-service
  
  # Configuración de Persistencia Externa
  datasource:
    url: ${DB_ORDER_URL:jdbc:postgresql://localhost:5433/orders_db}
    username: ${DB_ORDER_USER:postgres}
    password: ${DB_ORDER_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Conexión a Mensajería AWS SQS / LocalStack
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT:http://localhost:4566}

# Monitoreo de Salud (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized